name: lab04_magleo_2023210907
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  provider: ^6.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.26.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
